ALTER TABLE tb_ai_generation_task ADD COLUMN self_check_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED';
ALTER TABLE tb_ai_generation_task ADD COLUMN self_check_result_json CLOB;
ALTER TABLE tb_ai_generation_task ADD COLUMN self_check_attempt_count INT NOT NULL DEFAULT 0;
ALTER TABLE tb_ai_generation_task ADD COLUMN generation_provider VARCHAR(64);
ALTER TABLE tb_ai_generation_task ADD COLUMN generation_model VARCHAR(128);
ALTER TABLE tb_ai_generation_task ADD COLUMN generation_prompt_version VARCHAR(128);
ALTER TABLE tb_ai_generation_task ADD COLUMN generation_prompt_hash VARCHAR(64);
ALTER TABLE tb_ai_generation_task ADD COLUMN generation_temperature DECIMAL(8, 4);
ALTER TABLE tb_ai_generation_task ADD COLUMN review_provider VARCHAR(64);
ALTER TABLE tb_ai_generation_task ADD COLUMN review_model VARCHAR(128);
ALTER TABLE tb_ai_generation_task ADD COLUMN review_prompt_version VARCHAR(128);
ALTER TABLE tb_ai_generation_task ADD COLUMN review_prompt_hash VARCHAR(64);
ALTER TABLE tb_ai_generation_task ADD COLUMN review_temperature DECIMAL(8, 4);
ALTER TABLE tb_ai_generation_task ADD COLUMN input_mode VARCHAR(32) DEFAULT 'TEXT';
ALTER TABLE tb_ai_generation_task ADD COLUMN image_digest VARCHAR(64);
ALTER TABLE tb_ai_generation_task ADD COLUMN image_count INT NOT NULL DEFAULT 0;
ALTER TABLE tb_ai_generation_task ADD COLUMN input_token_count INT;
ALTER TABLE tb_ai_generation_task ADD COLUMN output_token_count INT;
ALTER TABLE tb_ai_generation_task ADD COLUMN review_input_token_count INT;
ALTER TABLE tb_ai_generation_task ADD COLUMN review_output_token_count INT;
ALTER TABLE tb_ai_generation_task ADD COLUMN warning_codes_json CLOB;
ALTER TABLE tb_ai_generation_task ADD COLUMN has_warnings BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tb_ai_generation_task ADD COLUMN total_review_batches INT NOT NULL DEFAULT 0;
ALTER TABLE tb_ai_generation_task ADD COLUMN completed_review_batches INT NOT NULL DEFAULT 0;
ALTER TABLE tb_ai_generation_task ADD COLUMN failed_review_batches INT NOT NULL DEFAULT 0;
ALTER TABLE tb_ai_generation_task ADD COLUMN reviewed_case_count INT NOT NULL DEFAULT 0;
ALTER TABLE tb_ai_generation_task ADD COLUMN supplemented_case_count INT NOT NULL DEFAULT 0;
ALTER TABLE tb_ai_generation_task ADD COLUMN coverage_completeness VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN';

ALTER TABLE tb_ai_case_candidate ADD COLUMN source_type VARCHAR(32) NOT NULL DEFAULT 'INITIAL_GENERATION';
ALTER TABLE tb_ai_case_candidate ADD COLUMN validation_status VARCHAR(32) NOT NULL DEFAULT 'VALID';
ALTER TABLE tb_ai_case_candidate ADD COLUMN validation_issues_json CLOB;
ALTER TABLE tb_ai_case_candidate ADD COLUMN duplicate_of_candidate_id VARCHAR(64);
ALTER TABLE tb_ai_case_candidate ADD COLUMN coverage_status VARCHAR(32) NOT NULL DEFAULT 'UNREVIEWED';
ALTER TABLE tb_ai_case_candidate ADD COLUMN verification_status VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED';
ALTER TABLE tb_ai_case_candidate ADD COLUMN supplement_basis VARCHAR(64);
ALTER TABLE tb_ai_case_candidate ADD COLUMN supplement_truncated BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS tb_ai_case_coverage_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coverage_item_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    item_no INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description CLOB,
    requirement_reference VARCHAR(1000),
    coverage_status VARCHAR(32) NOT NULL DEFAULT 'UNREVIEWED',
    covered_candidate_ids_json CLOB,
    evidence_json CLOB,
    issues_json CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_case_coverage_item_id UNIQUE (coverage_item_id),
    CONSTRAINT uk_ai_case_coverage_task_no UNIQUE (task_id, item_no)
);
CREATE INDEX IF NOT EXISTS idx_ai_case_coverage_task_status
    ON tb_ai_case_coverage_item (task_id, coverage_status);

CREATE TABLE IF NOT EXISTS tb_ai_case_review_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_run_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    run_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL DEFAULT 'TASK_EXECUTION',
    provider VARCHAR(64),
    model VARCHAR(128),
    prompt_version VARCHAR(128),
    prompt_hash VARCHAR(64),
    temperature DECIMAL(8, 4),
    total_batches INT NOT NULL DEFAULT 0,
    completed_batches INT NOT NULL DEFAULT 0,
    failed_batches INT NOT NULL DEFAULT 0,
    reviewed_case_count INT NOT NULL DEFAULT 0,
    supplemented_case_count INT NOT NULL DEFAULT 0,
    coverage_completeness VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    global_result_json CLOB,
    raw_output CLOB,
    error_code VARCHAR(64),
    error_message CLOB,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_case_review_run_id UNIQUE (review_run_id),
    CONSTRAINT uk_ai_case_review_task_no UNIQUE (task_id, run_no)
);
CREATE INDEX IF NOT EXISTS idx_ai_case_review_run_task_status
    ON tb_ai_case_review_run (task_id, status);

CREATE TABLE IF NOT EXISTS tb_ai_case_review_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_batch_id VARCHAR(64) NOT NULL,
    review_run_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    batch_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    candidate_ids_json CLOB NOT NULL,
    coverage_item_ids_json CLOB,
    snapshot_id VARCHAR(64),
    attempt_count INT NOT NULL DEFAULT 0,
    provider VARCHAR(64),
    model VARCHAR(128),
    request_id VARCHAR(128),
    input_token_count INT,
    output_token_count INT,
    raw_output CLOB,
    result_json CLOB,
    error_code VARCHAR(64),
    error_message CLOB,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_case_review_batch_id UNIQUE (review_batch_id),
    CONSTRAINT uk_ai_case_review_run_batch_no UNIQUE (review_run_id, batch_no)
);
CREATE INDEX IF NOT EXISTS idx_ai_case_review_batch_task_status
    ON tb_ai_case_review_batch (task_id, status);

CREATE TABLE IF NOT EXISTS tb_ai_case_candidate_review_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id VARCHAR(64) NOT NULL,
    candidate_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    review_run_id VARCHAR(64) NOT NULL,
    review_batch_id VARCHAR(64),
    content_version INT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    case_json CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_case_candidate_snapshot_id UNIQUE (snapshot_id)
);
CREATE INDEX IF NOT EXISTS idx_ai_case_candidate_snapshot_candidate
    ON tb_ai_case_candidate_review_snapshot (candidate_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_case_candidate_snapshot_run
    ON tb_ai_case_candidate_review_snapshot (review_run_id, review_batch_id);

CREATE TABLE IF NOT EXISTS tb_ai_case_candidate_suggestion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_id VARCHAR(64) NOT NULL,
    candidate_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    review_run_id VARCHAR(64),
    review_batch_id VARCHAR(64),
    based_on_content_version INT NOT NULL,
    based_on_content_hash VARCHAR(64) NOT NULL,
    suggested_content_json CLOB NOT NULL,
    issue_list_json CLOB,
    score INT,
    confidence DOUBLE,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_case_candidate_suggestion_id UNIQUE (suggestion_id)
);
CREATE INDEX IF NOT EXISTS idx_ai_case_candidate_suggestion_candidate
    ON tb_ai_case_candidate_suggestion (candidate_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_case_candidate_suggestion_run
    ON tb_ai_case_candidate_suggestion (review_run_id, review_batch_id);
