ALTER TABLE tb_ai_generation_task
    ADD COLUMN self_check_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' AFTER error_code,
    ADD COLUMN self_check_result_json MEDIUMTEXT NULL AFTER self_check_status,
    ADD COLUMN self_check_attempt_count INT NOT NULL DEFAULT 0 AFTER self_check_result_json,
    ADD COLUMN generation_provider VARCHAR(64) NULL AFTER model,
    ADD COLUMN generation_model VARCHAR(128) NULL AFTER generation_provider,
    ADD COLUMN generation_prompt_version VARCHAR(128) NULL AFTER generation_model,
    ADD COLUMN generation_prompt_hash VARCHAR(64) NULL AFTER generation_prompt_version,
    ADD COLUMN generation_temperature DECIMAL(8, 4) NULL AFTER generation_prompt_hash,
    ADD COLUMN review_provider VARCHAR(64) NULL AFTER generation_temperature,
    ADD COLUMN review_model VARCHAR(128) NULL AFTER review_provider,
    ADD COLUMN review_prompt_version VARCHAR(128) NULL AFTER review_model,
    ADD COLUMN review_prompt_hash VARCHAR(64) NULL AFTER review_prompt_version,
    ADD COLUMN review_temperature DECIMAL(8, 4) NULL AFTER review_prompt_hash,
    ADD COLUMN input_mode VARCHAR(32) NULL DEFAULT 'TEXT' AFTER asset_ids_json,
    ADD COLUMN image_digest VARCHAR(64) NULL AFTER input_mode,
    ADD COLUMN image_count INT NOT NULL DEFAULT 0 AFTER image_digest,
    ADD COLUMN input_token_count INT NULL AFTER image_count,
    ADD COLUMN output_token_count INT NULL AFTER input_token_count,
    ADD COLUMN review_input_token_count INT NULL AFTER output_token_count,
    ADD COLUMN review_output_token_count INT NULL AFTER review_input_token_count,
    ADD COLUMN warning_codes_json MEDIUMTEXT NULL AFTER review_raw_output,
    ADD COLUMN has_warnings TINYINT NOT NULL DEFAULT 0 AFTER warning_codes_json,
    ADD COLUMN total_review_batches INT NOT NULL DEFAULT 0 AFTER has_warnings,
    ADD COLUMN completed_review_batches INT NOT NULL DEFAULT 0 AFTER total_review_batches,
    ADD COLUMN failed_review_batches INT NOT NULL DEFAULT 0 AFTER completed_review_batches,
    ADD COLUMN reviewed_case_count INT NOT NULL DEFAULT 0 AFTER failed_review_batches,
    ADD COLUMN supplemented_case_count INT NOT NULL DEFAULT 0 AFTER reviewed_case_count,
    ADD COLUMN coverage_completeness VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' AFTER supplemented_case_count;

ALTER TABLE tb_ai_case_candidate
    ADD COLUMN source_type VARCHAR(32) NOT NULL DEFAULT 'INITIAL_GENERATION' AFTER origin,
    ADD COLUMN validation_status VARCHAR(32) NOT NULL DEFAULT 'VALID' AFTER content_hash,
    ADD COLUMN validation_issues_json MEDIUMTEXT NULL AFTER validation_status,
    ADD COLUMN duplicate_of_candidate_id VARCHAR(64) NULL AFTER validation_issues_json,
    ADD COLUMN coverage_status VARCHAR(32) NOT NULL DEFAULT 'UNREVIEWED' AFTER duplicate_of_candidate_id,
    ADD COLUMN verification_status VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED' AFTER coverage_status,
    ADD COLUMN supplement_basis VARCHAR(64) NULL AFTER verification_status,
    ADD COLUMN supplement_truncated TINYINT NOT NULL DEFAULT 0 AFTER supplement_basis;

CREATE TABLE IF NOT EXISTS tb_ai_case_coverage_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    coverage_item_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    item_no INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    requirement_reference VARCHAR(1000) NULL,
    coverage_status VARCHAR(32) NOT NULL DEFAULT 'UNREVIEWED',
    covered_candidate_ids_json MEDIUMTEXT NULL,
    evidence_json MEDIUMTEXT NULL,
    issues_json MEDIUMTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_case_coverage_item_id (coverage_item_id),
    UNIQUE KEY uk_ai_case_coverage_task_no (task_id, item_no),
    KEY idx_ai_case_coverage_task_status (task_id, coverage_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tb_ai_case_review_run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    review_run_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    run_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL DEFAULT 'TASK_EXECUTION',
    provider VARCHAR(64) NULL,
    model VARCHAR(128) NULL,
    prompt_version VARCHAR(128) NULL,
    prompt_hash VARCHAR(64) NULL,
    temperature DECIMAL(8, 4) NULL,
    total_batches INT NOT NULL DEFAULT 0,
    completed_batches INT NOT NULL DEFAULT 0,
    failed_batches INT NOT NULL DEFAULT 0,
    reviewed_case_count INT NOT NULL DEFAULT 0,
    supplemented_case_count INT NOT NULL DEFAULT 0,
    coverage_completeness VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    global_result_json MEDIUMTEXT NULL,
    raw_output MEDIUMTEXT NULL,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_case_review_run_id (review_run_id),
    UNIQUE KEY uk_ai_case_review_task_no (task_id, run_no),
    KEY idx_ai_case_review_run_task_status (task_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tb_ai_case_review_batch (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    review_batch_id VARCHAR(64) NOT NULL,
    review_run_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    batch_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    candidate_ids_json MEDIUMTEXT NOT NULL,
    coverage_item_ids_json MEDIUMTEXT NULL,
    snapshot_id VARCHAR(64) NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    provider VARCHAR(64) NULL,
    model VARCHAR(128) NULL,
    request_id VARCHAR(128) NULL,
    input_token_count INT NULL,
    output_token_count INT NULL,
    raw_output MEDIUMTEXT NULL,
    result_json MEDIUMTEXT NULL,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_case_review_batch_id (review_batch_id),
    UNIQUE KEY uk_ai_case_review_run_batch_no (review_run_id, batch_no),
    KEY idx_ai_case_review_batch_task_status (task_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tb_ai_case_candidate_review_snapshot (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    snapshot_id VARCHAR(64) NOT NULL,
    candidate_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    review_run_id VARCHAR(64) NOT NULL,
    review_batch_id VARCHAR(64) NULL,
    content_version INT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    case_json MEDIUMTEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_case_candidate_snapshot_id (snapshot_id),
    KEY idx_ai_case_candidate_snapshot_candidate (candidate_id, created_at),
    KEY idx_ai_case_candidate_snapshot_run (review_run_id, review_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tb_ai_case_candidate_suggestion (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    suggestion_id VARCHAR(64) NOT NULL,
    candidate_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    review_run_id VARCHAR(64) NULL,
    review_batch_id VARCHAR(64) NULL,
    based_on_content_version INT NOT NULL,
    based_on_content_hash VARCHAR(64) NOT NULL,
    suggested_content_json MEDIUMTEXT NOT NULL,
    issue_list_json MEDIUMTEXT NULL,
    score INT NULL,
    confidence DOUBLE NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_case_candidate_suggestion_id (suggestion_id),
    KEY idx_ai_case_candidate_suggestion_candidate (candidate_id, created_at),
    KEY idx_ai_case_candidate_suggestion_run (review_run_id, review_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
